# Generated by Django 5.0.1 on 2024-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_lastname',
            field=models.CharField(default='last_name', max_length=255, verbose_name='user_lastname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time_stamp'),
        ),
    ]
