# Generated by Django 5.0.1 on 2024-03-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='time_stamp')),
            ],
        ),
    ]
